### PR TITLE
Removal of an deprecated FSiFormExtensionsBundle in favor of IvoryCKEditorBundle

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by bartekgruszka** [comment]
You have to update [spec](https://github.com/fsi-open/admin-gallery-bundle/blob/master/spec/FSi/Bundle/AdminGalleryBundle/Form/Type/FSiAdminGallerySpec.php) too.

**Comment by bartekgruszka** [comment]
And please update [docs](https://github.com/fsi-open/admin-gallery-bundle/blob/master/Resources/doc/installation.md).

**Comment by szymach** [comment]
@bartekgruszka

**Comment by szymach** [comment]
@fsi-open requesting verification & merge

**Comment by chives** [comment]
:+1:

**Comment by JarekW** [comment]
:+1:

**Comment by bartekgruszka** [comment]
:+1:

**Pull request merged**
